name: "STONKS"

on:
  workflow_dispatch:
    # schedule:
    #   - cron: '*/5 * * * *'
    inputs:
      EOD_API_KEY:
        type: string
        required: true
        description: API key for eodhd api
      EOD_API_STOCK:
        type: string
        required: true
        description: The stock you want a report on, taken from https://eodhd.com/financial-apis/api-for-historical-data-and-volumes/
      TO_EMAILS:
        type: string
        required: true
        description: Comma+space separated list of emails, e.g 'test@test.com, test2@test.com, test3@test.com''
      FROM_EMAIL:
        type: string
        required: true
        description: Email that the notification is sent from - a valid sendgrid account email.
      SENDGRID_KEY:
        type: string
        required: true
        description: Sendgrid API key

env:
  EOD_API_KEY: ${{ inputs.EOD_API_KEY }}
  EOD_API_STOCK: ${{ inputs.EOD_API_STOCK }}
  SENDGRID_API_KEY: ${{ inputs.SENDGRID_API_KEY }}
  FROM_EMAIL: ${{ inputs.FROM_EMAIL}}
  WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}

jobs:
  get-stonky:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - name: install dependencies
        run: poetry install
      - run: make run
