name: "Send Stock Report"

on:
  workflow_dispatch:
    # schedule:
    #   - cron: '0 12 * * 4'
    inputs:
      EOD_API_STOCK:
        type: string
        default: "CODE.LSE"
        description: The eodhd api stock code for the stock you want to get a report on

env:
  EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
  EOD_API_STOCK: ${{ inputs.EOD_API_STOCK }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  TO_EMAILS: ${{ secrets.TO_EMAILS }}
  FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  Send:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - name: install dependencies
        run: poetry install
      - run: make run
